"""add last_sync_at to marketplace_accounts

Revision ID: 0f411e6cc3ad
Revises: 8143e8b429b0
Create Date: 2026-10-06 14:29:18.724673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f411e6cc3ad'
down_revision: Union[str, None] = '8143e8b429b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
