"""add delivery_services and link to sales

Revision ID: 3051d2547d3c
Revises: 0fac23dc6abb
Create Date: 2026-09-13 07:13:58.237372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3051d2547d3c'
down_revision: Union[str, None] = '0fac23dc6abb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_services_code'), 'delivery_services', ['code'], unique=True)
    op.add_column('sales', sa.Column('delivery_service_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sales_delivery_service_id'), 'sales', ['delivery_service_id'], unique=False)
    op.create_foreign_key(None, 'sales', 'delivery_services', ['delivery_service_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_index(op.f('ix_sales_delivery_service_id'), table_name='sales')
    op.drop_column('sales', 'delivery_service_id')
    op.drop_index(op.f('ix_delivery_services_code'), table_name='delivery_services')
    op.drop_table('delivery_services')
    # ### end Alembic commands ###
