"""add user.yandex_id for OAuth

Revision ID: 54a8c06fcfa8
Revises: 64dd44ca6d69
Create Date: 2026-10-09 12:55:35.687710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54a8c06fcfa8'
down_revision: Union[str, None] = '64dd44ca6d69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('yandex_id', sa.String(length=50), nullable=True))
    op.create_index(op.f('ix_users_yandex_id'), 'users', ['yandex_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_yandex_id'), table_name='users')
    op.drop_column('users', 'yandex_id')
    # ### end Alembic commands ###
