"""add unit economics fields to Sale model

Revision ID: 70dc36558692
Revises: 7d382019a15c
Create Date: 2026-09-15 08:27:37.642013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70dc36558692'
down_revision: Union[str, None] = '7d382019a15c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('commission_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('sales', sa.Column('return_logistics_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales', sa.Column('acquiring_fee', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales', sa.Column('acquiring_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('sales', sa.Column('storage_cost', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales', sa.Column('spp_percent', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('sales', sa.Column('spp_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('sales', sa.Column('retail_price_with_spp', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('sales', sa.Column('payout_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sales', 'payout_amount')
    op.drop_column('sales', 'retail_price_with_spp')
    op.drop_column('sales', 'spp_amount')
    op.drop_column('sales', 'spp_percent')
    op.drop_column('sales', 'storage_cost')
    op.drop_column('sales', 'acquiring_percent')
    op.drop_column('sales', 'acquiring_fee')
    op.drop_column('sales', 'return_logistics_cost')
    op.drop_column('sales', 'commission_percent')
    # ### end Alembic commands ###
