"""add unit economics fields to products

Revision ID: 7d382019a15c
Revises: bce189b5bc9d
Create Date: 2026-09-15 08:17:29.527273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d382019a15c'
down_revision: Union[str, None] = 'bce189b5bc9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('cost_price', sa.Numeric(precision=12, scale=2), nullable=True))
    op.add_column('products', sa.Column('volume_liters', sa.Numeric(precision=10, scale=3), nullable=True))
    op.add_column('products', sa.Column('length_cm', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('products', sa.Column('width_cm', sa.Numeric(precision=8, scale=2), nullable=True))
    op.add_column('products', sa.Column('height_cm', sa.Numeric(precision=8, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'height_cm')
    op.drop_column('products', 'width_cm')
    op.drop_column('products', 'length_cm')
    op.drop_column('products', 'volume_liters')
    op.drop_column('products', 'cost_price')
    # ### end Alembic commands ###
