"""add advertising_expenses table

Revision ID: 9b5cc11083dc
Revises: manual_last_sync_at
Create Date: 2026-10-07 14:29:49.149161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b5cc11083dc'
down_revision: Union[str, None] = 'manual_last_sync_at'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('advertising_expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_advertising_expenses_date_from'), 'advertising_expenses', ['date_from'], unique=False)
    op.create_index(op.f('ix_advertising_expenses_date_to'), 'advertising_expenses', ['date_to'], unique=False)
    op.create_index(op.f('ix_advertising_expenses_marketplace_id'), 'advertising_expenses', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_advertising_expenses_product_id'), 'advertising_expenses', ['product_id'], unique=False)
    op.create_index(op.f('ix_advertising_expenses_source'), 'advertising_expenses', ['source'], unique=False)
    op.create_index(op.f('ix_advertising_expenses_user_id'), 'advertising_expenses', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_advertising_expenses_user_id'), table_name='advertising_expenses')
    op.drop_index(op.f('ix_advertising_expenses_source'), table_name='advertising_expenses')
    op.drop_index(op.f('ix_advertising_expenses_product_id'), table_name='advertising_expenses')
    op.drop_index(op.f('ix_advertising_expenses_marketplace_id'), table_name='advertising_expenses')
    op.drop_index(op.f('ix_advertising_expenses_date_to'), table_name='advertising_expenses')
    op.drop_index(op.f('ix_advertising_expenses_date_from'), table_name='advertising_expenses')
    op.drop_table('advertising_expenses')
    # ### end Alembic commands ###
