"""add telegram_subscriptions

Revision ID: ad3c2bb462b0
Revises: 21392570acd4
Create Date: 2026-10-08 14:52:22.284380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad3c2bb462b0'
down_revision: Union[str, None] = '21392570acd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('telegram_username', sa.String(length=255), nullable=True),
    sa.Column('notify_new_sales', sa.Boolean(), nullable=False),
    sa.Column('notify_loss_making', sa.Boolean(), nullable=False),
    sa.Column('notify_daily_report', sa.Boolean(), nullable=False),
    sa.Column('notify_drr_high', sa.Boolean(), nullable=False),
    sa.Column('drr_threshold', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_notification_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_subscriptions_chat_id'), 'telegram_subscriptions', ['chat_id'], unique=True)
    op.create_index(op.f('ix_telegram_subscriptions_user_id'), 'telegram_subscriptions', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_subscriptions_user_id'), table_name='telegram_subscriptions')
    op.drop_index(op.f('ix_telegram_subscriptions_chat_id'), table_name='telegram_subscriptions')
    op.drop_table('telegram_subscriptions')
    # ### end Alembic commands ###
