"""add used_marketplace_identities

Revision ID: ae468ef25985
Revises: 93bc2e822510
Create Date: 2026-10-09 18:03:53.725720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae468ef25985'
down_revision: Union[str, None] = '93bc2e822510'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('used_marketplace_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('marketplace_code', sa.String(length=50), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('first_user_id', sa.Integer(), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['first_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_used_marketplace_identities_identity_hash'), 'used_marketplace_identities', ['identity_hash'], unique=True)
    op.create_index(op.f('ix_used_marketplace_identities_marketplace_code'), 'used_marketplace_identities', ['marketplace_code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_used_marketplace_identities_marketplace_code'), table_name='used_marketplace_identities')
    op.drop_index(op.f('ix_used_marketplace_identities_identity_hash'), table_name='used_marketplace_identities')
    op.drop_table('used_marketplace_identities')
    # ### end Alembic commands ###
