"""add subscription and trial_identity

Revision ID: bce189b5bc9d
Revises: f9e2ba23eb73
Create Date: 2026-09-14 10:24:48.788622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce189b5bc9d'
down_revision: Union[str, None] = 'f9e2ba23eb73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_external_id'), 'payments', ['external_id'], unique=True)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('trial_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('identity_hash', sa.String(length=64), nullable=False),
    sa.Column('email_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trial_identities_email_hash'), 'trial_identities', ['email_hash'], unique=False)
    op.create_index(op.f('ix_trial_identities_identity_hash'), 'trial_identities', ['identity_hash'], unique=True)
    op.create_index(op.f('ix_trial_identities_user_id'), 'trial_identities', ['user_id'], unique=False)
    op.add_column(
        'users',
        sa.Column('subscription_status', sa.String(length=20), nullable=False, server_default='none'),
    )
    op.add_column('users', sa.Column('trial_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('trial_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('subscription_ends_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_users_subscription_status'), 'users', ['subscription_status'], unique=False)
    op.alter_column('users', 'subscription_status', server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_status'), table_name='users')
    op.drop_column('users', 'subscription_ends_at')
    op.drop_column('users', 'trial_ends_at')
    op.drop_column('users', 'trial_started_at')
    op.drop_column('users', 'subscription_status')
    op.drop_index(op.f('ix_trial_identities_user_id'), table_name='trial_identities')
    op.drop_index(op.f('ix_trial_identities_identity_hash'), table_name='trial_identities')
    op.drop_index(op.f('ix_trial_identities_email_hash'), table_name='trial_identities')
    op.drop_table('trial_identities')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_external_id'), table_name='payments')
    op.drop_table('payments')
    # ### end Alembic commands ###
