"""add marketplace_accounts

Revision ID: daf35d9cd7a3
Revises: 3051d2547d3c
Create Date: 2026-09-13 10:45:42.534071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'daf35d9cd7a3'
down_revision: Union[str, None] = '3051d2547d3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('marketplace_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.String(length=100), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_marketplace_accounts_marketplace_id'), 'marketplace_accounts', ['marketplace_id'], unique=False)
    op.create_index(op.f('ix_marketplace_accounts_user_id'), 'marketplace_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_marketplace_accounts_user_id'), table_name='marketplace_accounts')
    op.drop_index(op.f('ix_marketplace_accounts_marketplace_id'), table_name='marketplace_accounts')
    op.drop_table('marketplace_accounts')
    # ### end Alembic commands ###
