"""add user.trial_revoked_reason

Revision ID: f204ac258125
Revises: ae468ef25985
Create Date: 2026-10-09 18:42:14.554753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f204ac258125'
down_revision: Union[str, None] = 'ae468ef25985'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('trial_revoked_reason', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'trial_revoked_reason')
    # ### end Alembic commands ###
