"""add unique constraint products user_id sku

Revision ID: f9e2ba23eb73
Revises: fd2ca9624772
Create Date: 2026-09-13 17:36:44.315973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9e2ba23eb73'
down_revision: Union[str, None] = 'fd2ca9624772'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_products_user_sku', 'products', ['user_id', 'sku'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_products_user_sku', 'products', type_='unique')
    # ### end Alembic commands ###
